# Generated by Django 5.1.3 on 2025-05-01 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marcacion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='horario_entrada',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='horario_refrigerio',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='horario_salida',
        ),
    ]
