# Generated by Django 5.1.1 on 2025-04-28 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('Administrador', 'Administrador'), ('Profesor', 'Profesor'), ('Estudiante', 'Estudiante')], default='Estudiante', max_length=50),
        ),
    ]
